/*
 Navicat Premium Dump SQL

 Source Server         : db
 Source Server Type    : PostgreSQL
 Source Server Version : 160002 (160002)
 Source Host           : localhost:5432
 Source Catalog        : store
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160002 (160002)
 File Encoding         : 65001

 Date: 27/10/2024 18:20:39
*/


-- ----------------------------
-- Sequence structure for address_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."address_seq";
CREATE SEQUENCE "public"."address_seq" 
INCREMENT 50
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."address_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for orders_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."orders_seq";
CREATE SEQUENCE "public"."orders_seq" 
INCREMENT 50
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."orders_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."product_id_seq";
CREATE SEQUENCE "public"."product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."product_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for users_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."users_seq";
CREATE SEQUENCE "public"."users_seq" 
INCREMENT 50
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."users_seq" OWNER TO "postgres";

-- ----------------------------
-- Table structure for address
-- ----------------------------
DROP TABLE IF EXISTS "public"."address";
CREATE TABLE "public"."address" (
  "id" int8 NOT NULL,
  "address" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "city" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "country" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "post_code" int4 NOT NULL,
  "state" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "version" int8
)
;
ALTER TABLE "public"."address" OWNER TO "postgres";

-- ----------------------------
-- Records of address
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for order_inventory_transaction_ids
-- ----------------------------
DROP TABLE IF EXISTS "public"."order_inventory_transaction_ids";
CREATE TABLE "public"."order_inventory_transaction_ids" (
  "order_id" int8 NOT NULL,
  "inventory_transaction_id" int8
)
;
ALTER TABLE "public"."order_inventory_transaction_ids" OWNER TO "postgres";

-- ----------------------------
-- Records of order_inventory_transaction_ids
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for orders
-- ----------------------------
DROP TABLE IF EXISTS "public"."orders";
CREATE TABLE "public"."orders" (
  "id" int8 NOT NULL,
  "available_warehouse" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "create_time" timestamp(6) NOT NULL,
  "deliver_status" varchar(255) COLLATE "pg_catalog"."default",
  "order_status" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "payment_status" varchar(255) COLLATE "pg_catalog"."default",
  "quantity" int4 NOT NULL,
  "tracking_number" varchar(255) COLLATE "pg_catalog"."default",
  "transaction_id" int8,
  "update_time" timestamp(6) NOT NULL,
  "version" int8,
  "product_id" int8 NOT NULL,
  "user_id" int8 NOT NULL
)
;
ALTER TABLE "public"."orders" OWNER TO "postgres";

-- ----------------------------
-- Records of orders
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS "public"."product";
CREATE TABLE "public"."product" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "description" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "image_url" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "price" numeric(38,2) NOT NULL,
  "version" int8,
  "warehouse_product_id" int8
)
;
ALTER TABLE "public"."product" OWNER TO "postgres";

-- ----------------------------
-- Records of product
-- ----------------------------
BEGIN;
INSERT INTO "public"."product" ("id", "description", "image_url", "name", "price", "version", "warehouse_product_id") VALUES (1, 'new Iphone', '/uploads/iphone16_1579317366374916.jpg', 'Iphone 88888 Pro Max', 10.00, 0, 1);
COMMIT;

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS "public"."users";
CREATE TABLE "public"."users" (
  "id" int8 NOT NULL,
  "account" varchar(255) COLLATE "pg_catalog"."default",
  "email" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "version" int8,
  "address_id" int8
)
;
ALTER TABLE "public"."users" OWNER TO "postgres";

-- ----------------------------
-- Records of users
-- ----------------------------
BEGIN;
INSERT INTO "public"."users" ("id", "account", "email", "password", "username", "version", "address_id") VALUES (1, '17300131876332692', 'admin@admin.com', 'iMRu8tMFiG0XkRxtnEfb7Co4b+nGZVwsEHlweuTGEgk=', 'admin', 0, NULL);
INSERT INTO "public"."users" ("id", "account", "email", "password", "username", "version", "address_id") VALUES (2, '17300132590858740', '123@123.com', 'iMRu8tMFiG0XkRxtnEfb7Co4b+nGZVwsEHlweuTGEgk=', 'customer', 0, NULL);
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."address_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."orders_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."product_id_seq"
OWNED BY "public"."product"."id";
SELECT setval('"public"."product_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"public"."users_seq"', 51, true);

-- ----------------------------
-- Primary Key structure for table address
-- ----------------------------
ALTER TABLE "public"."address" ADD CONSTRAINT "address_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Checks structure for table orders
-- ----------------------------
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_deliver_status_check" CHECK (deliver_status::text = ANY (ARRAY['CREATED'::character varying, 'PICKED_UP'::character varying, 'DELIVERING'::character varying, 'DELIVERED'::character varying, 'LOST'::character varying]::text[]));
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_order_status_check" CHECK (order_status::text = ANY (ARRAY['AWAITING_PAYMENT'::character varying, 'PENDING_ON_DELIVERY'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'PROCESSING_DELIVERY'::character varying]::text[]));

-- ----------------------------
-- Primary Key structure for table orders
-- ----------------------------
ALTER TABLE "public"."orders" ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for product
-- ----------------------------
SELECT setval('"public"."product_id_seq"', 1, true);

-- ----------------------------
-- Primary Key structure for table product
-- ----------------------------
ALTER TABLE "public"."product" ADD CONSTRAINT "product_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Uniques structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "uk6dotkott2kjsp8vw4d0m25fb7" UNIQUE ("email");
ALTER TABLE "public"."users" ADD CONSTRAINT "ukhbvhqvjgmhd5omxyo67ynvbyp" UNIQUE ("address_id");

-- ----------------------------
-- Primary Key structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table order_inventory_transaction_ids
-- ----------------------------
ALTER TABLE "public"."order_inventory_transaction_ids" ADD CONSTRAINT "fk35irascg4ub5wxxcf716irg24" FOREIGN KEY ("order_id") REFERENCES "public"."orders" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table orders
-- ----------------------------
ALTER TABLE "public"."orders" ADD CONSTRAINT "fk32ql8ubntj5uh44ph9659tiih" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."orders" ADD CONSTRAINT "fk787ibr3guwp6xobrpbofnv7le" FOREIGN KEY ("product_id") REFERENCES "public"."product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table users
-- ----------------------------
ALTER TABLE "public"."users" ADD CONSTRAINT "fkditu6lr4ek16tkxtdsne0gxib" FOREIGN KEY ("address_id") REFERENCES "public"."address" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
