/*
 Navicat Premium Dump SQL

 Source Server         : db
 Source Server Type    : PostgreSQL
 Source Server Version : 160002 (160002)
 Source Host           : localhost:5432
 Source Catalog        : warehouse
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160002 (160002)
 File Encoding         : 65001

 Date: 27/10/2024 18:21:16
*/


-- ----------------------------
-- Sequence structure for inventory_transaction_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."inventory_transaction_id_seq";
CREATE SEQUENCE "public"."inventory_transaction_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."inventory_transaction_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."product_id_seq";
CREATE SEQUENCE "public"."product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."product_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for warehouse_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."warehouse_id_seq";
CREATE SEQUENCE "public"."warehouse_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."warehouse_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Sequence structure for warehouse_product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."warehouse_product_id_seq";
CREATE SEQUENCE "public"."warehouse_product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."warehouse_product_id_seq" OWNER TO "postgres";

-- ----------------------------
-- Table structure for inventory_transaction
-- ----------------------------
DROP TABLE IF EXISTS "public"."inventory_transaction";
CREATE TABLE "public"."inventory_transaction" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "quantity" int4,
  "transaction_time" timestamp(6),
  "type" varchar(255) COLLATE "pg_catalog"."default",
  "product_id" int8,
  "warehouse_id" int8
)
;
ALTER TABLE "public"."inventory_transaction" OWNER TO "postgres";

-- ----------------------------
-- Records of inventory_transaction
-- ----------------------------
BEGIN;
COMMIT;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS "public"."product";
CREATE TABLE "public"."product" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "modify_time" timestamp(6),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "version" int8
)
;
ALTER TABLE "public"."product" OWNER TO "postgres";

-- ----------------------------
-- Records of product
-- ----------------------------
BEGIN;
INSERT INTO "public"."product" ("id", "modify_time", "name", "version") VALUES (1, '2024-10-27 18:14:44.813887', 'Iphone 88888 Pro Max', 0);
COMMIT;

-- ----------------------------
-- Table structure for warehouse
-- ----------------------------
DROP TABLE IF EXISTS "public"."warehouse";
CREATE TABLE "public"."warehouse" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "location" varchar(255) COLLATE "pg_catalog"."default",
  "modify_time" timestamp(6),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "version" int8
)
;
ALTER TABLE "public"."warehouse" OWNER TO "postgres";

-- ----------------------------
-- Records of warehouse
-- ----------------------------
BEGIN;
INSERT INTO "public"."warehouse" ("id", "location", "modify_time", "name", "version") VALUES (1, 'location1', '2024-10-27 18:18:35.315999', 'warehouse1', 0);
INSERT INTO "public"."warehouse" ("id", "location", "modify_time", "name", "version") VALUES (2, 'location2', '2024-10-27 18:18:39.903428', 'warehouse2', 0);
COMMIT;

-- ----------------------------
-- Table structure for warehouse_product
-- ----------------------------
DROP TABLE IF EXISTS "public"."warehouse_product";
CREATE TABLE "public"."warehouse_product" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "modify_time" timestamp(6),
  "quantity" int4,
  "version" int8,
  "product_id" int8,
  "warehouse_id" int8
)
;
ALTER TABLE "public"."warehouse_product" OWNER TO "postgres";

-- ----------------------------
-- Records of warehouse_product
-- ----------------------------
BEGIN;
INSERT INTO "public"."warehouse_product" ("id", "modify_time", "quantity", "version", "product_id", "warehouse_id") VALUES (1, '2024-10-27 18:18:47.77785', 5, 0, 1, 1);
INSERT INTO "public"."warehouse_product" ("id", "modify_time", "quantity", "version", "product_id", "warehouse_id") VALUES (2, '2024-10-27 18:18:47.781731', 5, 0, 1, 2);
COMMIT;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."inventory_transaction_id_seq"
OWNED BY "public"."inventory_transaction"."id";
SELECT setval('"public"."inventory_transaction_id_seq"', 1, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."product_id_seq"
OWNED BY "public"."product"."id";
SELECT setval('"public"."product_id_seq"', 1, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."warehouse_id_seq"
OWNED BY "public"."warehouse"."id";
SELECT setval('"public"."warehouse_id_seq"', 2, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."warehouse_product_id_seq"
OWNED BY "public"."warehouse_product"."id";
SELECT setval('"public"."warehouse_product_id_seq"', 2, true);

-- ----------------------------
-- Auto increment value for inventory_transaction
-- ----------------------------
SELECT setval('"public"."inventory_transaction_id_seq"', 1, false);

-- ----------------------------
-- Checks structure for table inventory_transaction
-- ----------------------------
ALTER TABLE "public"."inventory_transaction" ADD CONSTRAINT "inventory_transaction_type_check" CHECK (type::text = ANY (ARRAY['IN'::character varying, 'OUT'::character varying, 'HOLD'::character varying, 'UNHOLD'::character varying]::text[]));

-- ----------------------------
-- Primary Key structure for table inventory_transaction
-- ----------------------------
ALTER TABLE "public"."inventory_transaction" ADD CONSTRAINT "inventory_transaction_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for product
-- ----------------------------
SELECT setval('"public"."product_id_seq"', 1, true);

-- ----------------------------
-- Primary Key structure for table product
-- ----------------------------
ALTER TABLE "public"."product" ADD CONSTRAINT "product_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for warehouse
-- ----------------------------
SELECT setval('"public"."warehouse_id_seq"', 2, true);

-- ----------------------------
-- Primary Key structure for table warehouse
-- ----------------------------
ALTER TABLE "public"."warehouse" ADD CONSTRAINT "warehouse_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Auto increment value for warehouse_product
-- ----------------------------
SELECT setval('"public"."warehouse_product_id_seq"', 2, true);

-- ----------------------------
-- Primary Key structure for table warehouse_product
-- ----------------------------
ALTER TABLE "public"."warehouse_product" ADD CONSTRAINT "warehouse_product_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table inventory_transaction
-- ----------------------------
ALTER TABLE "public"."inventory_transaction" ADD CONSTRAINT "fkadysxy0xx1oug9ljtg47bkcny" FOREIGN KEY ("product_id") REFERENCES "public"."product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."inventory_transaction" ADD CONSTRAINT "fkdicavw4luy0qi1gm7qqwhe0e6" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table warehouse_product
-- ----------------------------
ALTER TABLE "public"."warehouse_product" ADD CONSTRAINT "fk2m5r3qy83vqcqlkgr6n815mcn" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."warehouse_product" ADD CONSTRAINT "fkocdf46rpj8qoy9cqurnrvopr5" FOREIGN KEY ("product_id") REFERENCES "public"."product" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
